# Encoding String (Categoric, Object) Data

- **One-Hot Encoding:** Converts each category into separate binary columns, making no assumption about order.  
- **Label Encoding:** Assigns a unique integer to each category but may introduce unintended ordinal relationships.  
- **Ordinal Encoding:** Encodes categories with a defined order using integer values that preserve ranking.  
- **Target Encoding:** Replaces each category with the mean of the target variable for that category.  
- **Frequency Encoding:** Maps each category to its frequency (or count) in the dataset.  
- **Binary Encoding:** Converts categories into binary numbers to reduce dimensionality compared to one-hot encoding.  
- **Embedding:** Represents categories as dense numerical vectors learned during model training, commonly used in deep learning.

For can use these encoding methods firstly we find categoric data

## OneHotEncoding

In [17]:
import pandas as pd

df = pd.read_csv('../job_salary_prediction_dataset.csv')

In [18]:
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

Don't apply these encoder without seperate X and y columns.
Don't apply these encoder without seperate train and test data.

In [19]:
X = df.drop(["salary"],axis = 1)
y = df["salary"]

In [30]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
  X,
  y,
  random_state=42,
  test_size=0.2
)

In [31]:
categoric_X_train = X_train.select_dtypes(include=['category','object']).columns
categoric_X_test = X_test.select_dtypes(include=['category','object']).columns

/var/folders/3s/w63y6jxn56g83g0w4fgb4nh00000gn/T/ipykernel_28922/1798482697.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categoric_X_train = X_train.select_dtypes(include=['category','object']).columns
/var/folders/3s/w63y6jxn56g83g0w4fgb4nh00000gn/T/ipykernel_28922/1798482697.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categoric_X_test = X_test.select_dtypes(include=['category','object']).columns

In [34]:
from sklearn.preprocessing import OneHotEncoder

one_hot_x = OneHotEncoder(handle_unknown="ignore", sparse_output=False)

encoded_train = pd.DataFrame(
    one_hot_x.fit_transform(X_train[categoric_X_train]),
    columns=one_hot_x.get_feature_names_out(categoric_X_train),
    index=X_train.index
)

encoded_test = pd.DataFrame(
    one_hot_x.transform(X_test[categoric_X_test]),   
    columns=one_hot_x.get_feature_names_out(categoric_X_test),
    index=X_test.index
)

X_train = X_train.drop(columns=categoric_X_train).join(encoded_train)
X_test  = X_test.drop(columns=categoric_X_test).join(encoded_test)

In [35]:
X_train.head()

,experience_years,skills_count,certifications,job_title_AI Engineer,job_title_Backend Developer,job_title_Business Analyst,job_title_Cloud Engineer,job_title_Cybersecurity Analyst,job_title_Data Analyst,job_title_Data Scientist,...,location_India,location_Netherlands,location_Remote,location_Singapore,location_Sweden,location_UK,location_USA,remote_work_Hybrid,remote_work_No,remote_work_Yes
75381,4,14,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
65569,1,6,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
163473,16,3,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90518,4,18,4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
138866,7,8,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

# Label Encoding

Label Encoding does not support multiple columns directly.

In [45]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split


X_train,X_test,y_train,y_test = train_test_split(
  X,
  y,
  random_state=42,
  test_size=0.2
)

In [46]:
encoders = {}

for col in categoric_X_train:
    encoders[col] = LabelEncoder()
    X_train[col] = encoders[col].fit_transform(X_train[col])
    X_test[col]  = encoders[col].transform(X_test[col])

# Ordinal Encoder

In [47]:
from sklearn.preprocessing import OrdinalEncoder

ordinal_encoder = OrdinalEncoder()

In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
  X,
  y,
  random_state=42,
  test_size=0.2
)

In [50]:
categoric_X = X_train.select_dtypes(include=['object','category']).columns

X_train[categoric_X] = ordinal_encoder.fit_transform(X_train[categoric_X])
X_test[categoric_X] = ordinal_encoder.transform(X_test[categoric_X])

/var/folders/3s/w63y6jxn56g83g0w4fgb4nh00000gn/T/ipykernel_28922/1173891471.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categoric_X = X_train.select_dtypes(include=['object','category']).columns

# Target Encoding

In [51]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
  X,
  y,
  random_state=42,
  test_size=0.2
)

In [53]:
%pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in /opt/homebrew/lib/python3.11/site-packages (from category_encoders) (2.4.3)
Requirement already satisfied: pandas>=1.0.5 in /opt/homebrew/lib/python3.11/site-packages (from category_encoders) (3.0.1)
Collecting patsy>=0.5.1 (from category_encoders)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: scikit-learn>=1.6.0 in /opt/homebrew/lib/python3.11/site-packages (from category_encoders) (1.8.0)
Requirement already satisfied: scipy>=1.0.0 in /opt/homebrew/lib/python3.11/site-packages (from category_encoders) (1.17.1)
Collecting statsmodels>=0.9.0 (from category_encoders)
  Downloading statsmodels-0.14.6-cp311-cp311-macosx_11_0_arm64.whl.metadata (9.5 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/eraykosterelioglu/Library/Python/3.11/lib/python/site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/eraykosterelioglu/Library/Python/3.11/lib/python/site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in /opt/homebrew/lib/python3.11/site-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /opt/homebrew/lib/python3.11/site-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /Users/eraykosterelioglu/Library/Python/3.11/lib/python/site-packages (from statsmodels>=0.9.0->category_encoders) (26.0)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Downloading statsmodels-0.14.6-cp311-cp311-macosx_11_0_arm64.whl (10.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 4.8 MB/s  0:00:02eta 0:00:01
Installing collected packages: patsy, statsmodels, category_encoders
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [category_encoders]statsmodels]
Successfully installed category_encoders-2.9.0 patsy-1.0.2 statsmodels-0.14.6

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: /opt/homebrew/opt/python@3.11/bin/python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [54]:
import category_encoders as ce

encoder = ce.TargetEncoder(cols=list(categoric_X_train))

In [55]:
categoric_X = X_train.select_dtypes(include=['object','category']).columns

X_train[categoric_X] = encoder.fit_transform(X_train[categoric_X_train], y_train)
X_test[categoric_X_test]   = encoder.transform(X_test[categoric_X_test])

/var/folders/3s/w63y6jxn56g83g0w4fgb4nh00000gn/T/ipykernel_28922/2283615877.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categoric_X = X_train.select_dtypes(include=['object','category']).columns

In [56]:
X_train.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications
75381,163280.131947,4,137026.202257,14,145792.601995,141487.143482,97702.145519,149257.405252,5
65569,139269.183482,1,163923.449817,6,145396.747159,155673.401233,139376.977764,149257.405252,1
163473,139269.183482,16,131731.579959,3,145861.284639,141487.143482,167387.330125,143958.165142,1
90518,119755.327683,4,131731.579959,18,145863.182243,127337.465626,160112.487939,143961.999880,4
138866,139269.183482,7,137026.202257,8,145164.786889,141487.143482,153284.638522,143958.165142,0

# Normalization

We have different normalization methods that can transform data into new structure.  
Algorithms can process these normalized data on the same scale.

1. **Standard Scaler**: It is known as z-normalization and uses mean and variance.
2. **Min-Max Scaler**: This method uses min and max values.
3. **Box-Cox Transformation**: The Box-Cox transformation uses a power transformation method. It reduces right skewness and makes the distribution closer to normal.
4. **Yeo-Johnson Transformation**: The Yeo–Johnson transformation can handle both positive and negative values. It reduces skewness and makes the distribution closer to normal.

# Standard Scaler Application With Sklearn

In [1]:
import pandas as pd

feature_extraction.ipynb    numpy_operations.ipynb
feature_selection.ipynb     pandas_operations.ipynb
matplotlib_operations.ipynb

In [67]:
data_path = '../job_salary_prediction_dataset.csv'

df = pd.read_csv(data_path)

In [8]:
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

In [68]:
y = df['salary']

In [69]:
X = df.drop(['salary'],axis = 1)

If you use normalization method before data splitting can be data leakage.

In [83]:
from sklearn.model_selection import train_test_split

In [84]:
X_train,X_test,y_train,y_test = train_test_split(
  X,
  y,
  random_state=42,
  test_size=0.20
)

In [85]:
X_numeric = X.select_dtypes(include=['number']).columns

In [86]:
X_scaler = StandardScaler()
y_scaler = StandardScaler()

Don't use fit transform for test data. It can cause data leakage

Most of machine learning algorithm does not need scaled output.

In [87]:
X_train[X_numeric] = X_scaler.fit_transform(X_train[X_numeric])
X_test[X_numeric] = X_scaler.fit_transform(X_test[X_numeric])

# Yeo-Johnson Applying

In [88]:
X = df.drop(['salary'],axis = 1)
y = df['salary']

In [92]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
  X,
  y,
  random_state=42,
  test_size=0.2
)

In [91]:
from sklearn.preprocessing import PowerTransformer

pt = PowerTransformer()

In [93]:
numeric_values = X.select_dtypes(include=['number']).columns

X_train[numeric_values] = pt.fit_transform(X_train[numeric_values])
X_test[numeric_values] = pt.transform(X_test[numeric_values])