There is different selection and processing algorithm like OneHoteEncoding and Imputer.

One Hot Encoding converts categoric data to binary data it is useful for Deep Learning algorithms.
Imputing operiations fill missing values with mean, median etc.

In [4]:
from sklearn.impute import SimpleImputer
import pandas as pd

In [10]:
data = pd.read_csv("../job_salary_prediction_dataset.csv")

In [11]:
data.head()

            job_title  experience_years  ... certifications  salary
0         AI Engineer                10  ...              2  109413
1        Data Analyst                 5  ...              0   93764
2  Frontend Developer                18  ...              1  148123
3    Business Analyst                19  ...              0  189123
4     Product Manager                15  ...              0  165069

[5 rows x 10 columns]

In [12]:
df_categoric = data.select_dtypes(include = ['object','category','string'])

In [13]:
df_categoric.head()

            job_title education_level  ...   location remote_work
0         AI Engineer        Bachelor  ...      India      Hybrid
1        Data Analyst        Bachelor  ...  Australia          No
2  Frontend Developer             PhD  ...  Singapore          No
3    Business Analyst             PhD  ...     Canada         Yes
4     Product Manager        Bachelor  ...     Sweden         Yes

[5 rows x 6 columns]

In [23]:
df_numeric = data.select_dtypes(include = ['number'])

In [24]:
df_numeric.head()

   experience_years  skills_count  certifications  salary
0                10             2               2  109413
1                 5            17               0   93764
2                18             4               1  148123
3                19            13               0  189123
4                15             7               0  165069

In [25]:
df_numeric.isnull().sum()

experience_years    0
skills_count        0
certifications      0
salary              0
dtype: int64

In [26]:
import numpy as np

imputer = SimpleImputer(missing_values = np.nan,strategy = "mean")
df_numeric = imputer.fit_transform(df_numeric)

In [27]:
df_categoric = pd.get_dummies(df_categoric)

In [29]:
df_categoric.head()

   job_title_AI Engineer  ...  remote_work_Yes
0                   True  ...            False
1                  False  ...            False
2                  False  ...            False
3                  False  ...             True
4                  False  ...             True

[5 rows x 45 columns]

In [ ]:
df_categoric_2 = data.select_dtypes(include = ['object','category','string'])

In [37]:
from sklearn.preprocessing import OneHotEncoder

one_hot_encoder = OneHotEncoder(sparse_output = False)

df_categoric_2 = one_hot_encoder.fit_transform(df_categoric_2)

In [38]:
df_categoric_2 = pd.DataFrame(df_categoric_2)

In [39]:
df_categoric_2.head()

    0    1    2    3    4    5    6   ...   38   39   40   41   42   43   44
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  1.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  1.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0  0.0  0.0  1.0  0.0
3  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  1.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0  0.0  0.0  0.0  1.0

[5 rows x 45 columns]