# Linear Regression

In [25]:
import pandas as pd

df = pd.read_csv('../job_salary_prediction_dataset.csv')

In [2]:
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  str
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  str
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  str
 5   company_size      250000 non-null  str
 6   location          250000 non-null  str
 7   remote_work       250000 non-null  str
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), str(6)
memory usage: 19.1 MB

In [4]:
df.describe()

       experience_years   skills_count  certifications         salary
count     250000.000000  250000.000000   250000.000000  250000.000000
mean          10.005408       9.997812        2.491928  145718.080524
std            6.060602       5.479288        1.706475   37407.952729
min            0.000000       1.000000        0.000000   31867.000000
25%            5.000000       5.000000        1.000000  119358.000000
50%           10.000000      10.000000        2.000000  143453.000000
75%           15.000000      15.000000        4.000000  169492.000000
max           20.000000      19.000000        5.000000  333046.000000

In [26]:
X = df.drop('salary',axis = 1)
y = df['salary']

In [27]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
  X,
  y,
  random_state=42,
  test_size=0.2
)

In [28]:
from sklearn.linear_model import LinearRegression


linear_reg = LinearRegression(
  positive=True,
  n_jobs=5
)

In [29]:
categoric_data = X.select_dtypes(include=['object','category']).columns

/var/folders/3s/w63y6jxn56g83g0w4fgb4nh00000gn/T/ipykernel_6174/3012932348.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categoric_data = X.select_dtypes(include=['object','category']).columns

In [30]:
from sklearn.preprocessing import OneHotEncoder

one_hot = OneHotEncoder(sparse_output=False)

In [31]:
X_train_one_hot = one_hot.fit_transform(X_train[categoric_data])
X_test_one_hot = one_hot.transform(X_test[categoric_data])

In [33]:
X_train_one_hot

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 1., 0., 0.]], shape=(200000, 45))

In [34]:
encoded_X = one_hot.get_feature_names_out(categoric_data)

In [35]:
encoded_X

array(['job_title_AI Engineer', 'job_title_Backend Developer',
       'job_title_Business Analyst', 'job_title_Cloud Engineer',
       'job_title_Cybersecurity Analyst', 'job_title_Data Analyst',
       'job_title_Data Scientist', 'job_title_DevOps Engineer',
       'job_title_Frontend Developer',
       'job_title_Machine Learning Engineer', 'job_title_Product Manager',
       'job_title_Software Engineer', 'education_level_Bachelor',
       'education_level_Diploma', 'education_level_High School',
       'education_level_Master', 'education_level_PhD',
       'industry_Consulting', 'industry_Education', 'industry_Finance',
       'industry_Government', 'industry_Healthcare',
       'industry_Manufacturing', 'industry_Media', 'industry_Retail',
       'industry_Technology', 'industry_Telecom',
       'company_size_Enterprise', 'company_size_Large',
       'company_size_Medium', 'company_size_Small',
       'company_size_Startup', 'location_Australia', 'location_Canada',
       'location_Germany', 'location_India', 'location_Netherlands',
       'location_Remote', 'location_Singapore', 'location_Sweden',
       'location_UK', 'location_USA', 'remote_work_Hybrid',
       'remote_work_No', 'remote_work_Yes'], dtype=object)

In [36]:
X_train_one_hot = pd.DataFrame(X_train_one_hot,columns=encoded_X,index=X_train.index)
X_test_one_hot = pd.DataFrame(X_test_one_hot,columns=encoded_X,index=X_test.index)

In [37]:
X_train_one_hot

,job_title_AI Engineer,job_title_Backend Developer,job_title_Business Analyst,job_title_Cloud Engineer,job_title_Cybersecurity Analyst,job_title_Data Analyst,job_title_Data Scientist,job_title_DevOps Engineer,job_title_Frontend Developer,job_title_Machine Learning Engineer,...,location_India,location_Netherlands,location_Remote,location_Singapore,location_Sweden,location_UK,location_USA,remote_work_Hybrid,remote_work_No,remote_work_Yes
75381,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
65569,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
163473,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90518,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
138866,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119879,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
103694,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
131932,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
146867,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
121958,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [14]:
X_train = X_train.drop(columns = categoric_data).join(X_train_one_hot)
X_test = X_test.drop(columns = categoric_data).join(X_test_one_hot)

In [15]:
model = linear_reg.fit(X_train,y_train)

In [17]:
from sklearn.metrics import r2_score

y_preds = model.predict(X_test)

r2_score_new = r2_score(y_test,y_preds)

r2_score_new

0.9634692445007607

# Decision Tree Regressor

In [18]:
from sklearn.tree import DecisionTreeRegressor

reg_1 = DecisionTreeRegressor(
  max_depth=5,
)
reg_2 = DecisionTreeRegressor(
  max_depth=2
)
reg_3 = DecisionTreeRegressor(
  max_depth=8
)

In [19]:
decision_model_1 = reg_1.fit(X_train,y_train)
decision_model_2 = reg_2.fit(X_train,y_train)
decision_model_3 = reg_3.fit(X_train,y_train)

In [26]:
pred_dict = {

}

In [27]:
for model in decision_tree_list:

  y_pred = model.predict(X_test)
  r2_s = r2_score(y_test,y_pred)
  pred_dict[model] = r2_s

In [28]:
pred_dict

{DecisionTreeRegressor(max_depth=5): 0.577523450195988,
 DecisionTreeRegressor(max_depth=2): 0.32503426792622947,
 DecisionTreeRegressor(max_depth=8): 0.7291758832974798}

In [29]:
reg_4= DecisionTreeRegressor(
  max_depth=15
)

In [30]:
decision_model_4 = reg_4.fit(X_train,y_train)

In [32]:
y_pred = decision_model_4.predict(X_test)
r2_model_4 = r2_score(y_test,y_pred)
r2_model_4

0.9131220635462047

Since the data is large, he score increases as the depth increases

# Polynomal Regression

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('../job_salary_prediction_dataset.csv')

In [5]:
X = df.drop('salary',axis = 1)
y = df['salary']

In [6]:
from sklearn.preprocessing import PolynomialFeatures

poly_reg_2 = PolynomialFeatures(degree=2)
poly_reg_3 = PolynomialFeatures(degree=3)

In [7]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
  X,
  y,
  random_state=42,
  test_size=0.2
)

In [8]:
numeric_col = X.select_dtypes(include=['number']).columns

In [9]:
X_train_poly_2 = poly_reg_2.fit_transform(X_train[numeric_col])
X_test_poly_2 = poly_reg_2.transform(X_test[numeric_col])

In [10]:
X_train_poly_3 = poly_reg_3.fit_transform(X_train[numeric_col])
X_test_poly_3 = poly_reg_3.transform(X_test[numeric_col])

In [12]:
categoric_col = X.select_dtypes(include=['category','object']).columns

/var/folders/3s/w63y6jxn56g83g0w4fgb4nh00000gn/T/ipykernel_6174/2833514811.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categoric_col = X.select_dtypes(include=['category','object']).columns

In [13]:
from sklearn.preprocessing import OrdinalEncoder

ord_encoder = OrdinalEncoder()

In [14]:
X_train_encoded = ord_encoder.fit_transform(X_train[categoric_col])
X_test_encoded = ord_encoder.transform(X_test[categoric_col])

In [17]:
import numpy as np

In [18]:
import numpy as np

X_train_poly_2_last = np.hstack([X_train_poly_2, X_train_encoded])
X_test_poly_2_last = np.hstack([X_test_poly_2, X_test_encoded])

In [20]:
from sklearn.linear_model import LinearRegression

linear_reg = LinearRegression()

model = linear_reg.fit(X_train_poly_2_last,y_train)

In [22]:
y_preds = model.predict(X_test_poly_2_last)

In [23]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

r2_score_l = r2_score(y_test,y_preds)
mae_score_l = mean_absolute_error(y_test,y_preds)
mse = mean_squared_error(y_test,y_preds)

In [24]:
r2_score_l,mae_score_l,mse

(0.4559528143844379, 21740.731551499397, 756151398.3862017)

# We can see some preprocessing method does not work well.