# Regression is a method used to predict continous numerical values based on input variables.

In [1]:
import pandas as pd

df = pd.read_csv('../job_salary_prediction_dataset.csv')

In [2]:
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

In [3]:
df.tail()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
249995,Software Engineer,17,PhD,2,Telecom,Enterprise,India,No,1,127791
249996,Frontend Developer,20,PhD,7,Telecom,Startup,Remote,No,2,154593
249997,Business Analyst,1,Bachelor,12,Retail,Enterprise,India,Yes,0,75988
249998,Data Scientist,0,High School,2,Consulting,Small,Sweden,Hybrid,5,90467
249999,Data Analyst,16,Diploma,2,Technology,Medium,UK,No,5,133084

In [4]:
X = df.drop('salary',axis=1)

In [5]:
X.isnull().sum()

job_title           0
experience_years    0
education_level     0
skills_count        0
industry            0
company_size        0
location            0
remote_work         0
certifications      0
dtype: int64

In [5]:
y = df['salary']

In [6]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
  X,
  y,
  random_state=42,
  test_size=0.2
)

In [8]:
X_train.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications
75381,Machine Learning Engineer,4,Diploma,14,Technology,Medium,India,Yes,5
65569,Backend Developer,1,PhD,6,Consulting,Large,Sweden,Yes,1
163473,Backend Developer,16,High School,3,Manufacturing,Medium,Canada,No,1
90518,Data Analyst,4,High School,18,Finance,Startup,UK,Hybrid,4
138866,Backend Developer,7,Diploma,8,Retail,Medium,Germany,No,0

In [7]:
from sklearn.impute import SimpleImputer
import numpy as np

imputer_X = SimpleImputer(missing_values=np.nan,strategy = "median")

In [8]:
numeric_X = X.select_dtypes(include=['number']).columns

X_train[numeric_X] = imputer_X.fit_transform(X_train[numeric_X])
X_test[numeric_X] = imputer_X.transform(X_test[numeric_X])

In [11]:
X_train.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications
75381,Machine Learning Engineer,4.0,Diploma,14.0,Technology,Medium,India,Yes,5.0
65569,Backend Developer,1.0,PhD,6.0,Consulting,Large,Sweden,Yes,1.0
163473,Backend Developer,16.0,High School,3.0,Manufacturing,Medium,Canada,No,1.0
90518,Data Analyst,4.0,High School,18.0,Finance,Startup,UK,Hybrid,4.0
138866,Backend Developer,7.0,Diploma,8.0,Retail,Medium,Germany,No,0.0

In [9]:
correlation = X[numeric_X].corr()
correlation

                  experience_years  skills_count  certifications
experience_years          1.000000      0.000149       -0.000198
skills_count              0.000149      1.000000       -0.002230
certifications           -0.000198     -0.002230        1.000000

In [10]:
categoric_X = X.select_dtypes(include=['category','object']).columns

/var/folders/3s/w63y6jxn56g83g0w4fgb4nh00000gn/T/ipykernel_13346/763339343.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categoric_X = X.select_dtypes(include=['category','object']).columns

In [11]:
from sklearn.preprocessing import OneHotEncoder

one = OneHotEncoder(sparse_output=False)

In [13]:
X_train_one_hote = one.fit_transform(X_train[categoric_X])
X_test_one_hote= one.transform(X_test[categoric_X])

In [14]:
encoded_columns = one.get_feature_names_out(categoric_X)

In [15]:
X_train_one_hote = pd.DataFrame(X_train_one_hote,columns=encoded_columns,index=X_train.index)
X_test_one_hote = pd.DataFrame(X_test_one_hote,columns=encoded_columns,index=X_test.index)

In [20]:
X_train = X_train.drop(columns=categoric_X).join(X_train_one_hote)
X_test = X_test.drop(columns=categoric_X).join(X_test_one_hote)

In [21]:
X_train

,experience_years,skills_count,certifications,job_title_AI Engineer,job_title_Backend Developer,job_title_Business Analyst,job_title_Cloud Engineer,job_title_Cybersecurity Analyst,job_title_Data Analyst,job_title_Data Scientist,...,location_India,location_Netherlands,location_Remote,location_Singapore,location_Sweden,location_UK,location_USA,remote_work_Hybrid,remote_work_No,remote_work_Yes
75381,4.0,14.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
65569,1.0,6.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
163473,16.0,3.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90518,4.0,18.0,4.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
138866,7.0,8.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119879,3.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
103694,7.0,6.0,4.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
131932,6.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
146867,7.0,8.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
121958,12.0,10.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [22]:
X_train.shape

(200000, 48)

In [23]:
from sklearn import ensemble
import xgboost as xgb
import lightgbm as lgb

ada_boost_regressor = ensemble.AdaBoostRegressor()

extra_trees_regressor = ensemble.ExtraTreesRegressor()
gradient_boosting_regressor = ensemble.GradientBoostingRegressor()
hist_gradient_boosting_regressor = ensemble.HistGradientBoostingRegressor()
random_forest_regressor = ensemble.RandomForestRegressor()

stacking_regressor = ensemble.StackingRegressor(
    estimators=[
        ('gb', gradient_boosting_regressor),
        ('rf',random_forest_regressor),
    ]
)
bagging_regressor = ensemble.BaggingRegressor(
)

xgb_regressor = xgb.XGBRegressor()
lgb_regressor = lgb.LGBMRegressor()

models = {
    "ada_boost": ada_boost_regressor,
    "bagging": bagging_regressor,
    "extra_trees": extra_trees_regressor,
    "gradient_boosting": gradient_boosting_regressor,
    "hist_gradient_boosting": hist_gradient_boosting_regressor,
    "random_forest": random_forest_regressor,
    "stacking": stacking_regressor,
    "xgboost": xgb_regressor,
    "lightgbm": lgb_regressor
}

In [25]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [30]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

results = {}

for name, model in models.items():

    trained_model = model.fit(X_train, y_train)
    y_preds = trained_model.predict(X_test)

    r2_n = r2_score(y_test, y_preds)
    mae = mean_absolute_error(y_test, y_preds)
    mse = mean_squared_error(y_test, y_preds)
    rmse = np.sqrt(mse)

    results[name] = {
        "R2": r2_n,
        "MAE": mae,
        "MSE": mse,
        "RMSE": rmse
    }

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000721 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 137
[LightGBM] [Info] Number of data points in the train set: 200000, number of used features: 48
[LightGBM] [Info] Start training from score 145713.972810

In [33]:
results = pd.DataFrame(results)

In [34]:
results

,ada_boost,bagging,extra_trees,gradient_boosting,hist_gradient_boosting,random_forest,stacking,xgboost,lightgbm
R2,7.889946e-01,9.675346e-01,9.694066e-01,9.493268e-01,9.782423e-01,9.712118e-01,-8.084288e-01,9.788591e-01,9.781865e-01
MAE,1.377413e+04,5.322457e+03,5.179843e+03,6.595432e+03,4.375036e+03,5.019322e+03,3.984874e+04,4.321996e+03,4.383165e+03
MSE,2.932687e+08,4.512250e+07,4.252062e+07,7.042890e+07,3.024029e+07,4.001165e+07,2.513469e+09,2.938293e+07,3.031774e+07
RMSE,1.712509e+04,6.717328e+03,6.520784e+03,8.392193e+03,5.499117e+03,6.325476e+03,5.013451e+04,5.420602e+03,5.506155e+03

# Random Forest Regressor

In [20]:
import pandas as pd

df = pd.read_csv('../job_salary_prediction_dataset.csv')

In [21]:
X = df.drop('salary',axis = 1)
y = df['salary']

In [22]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
  X,
  y,
  random_state=42,
  test_size=0.2
)

In [24]:
from sklearn.ensemble import RandomForestRegressor

randomforest_reg = RandomForestRegressor(
  random_state=42,
  n_estimators=100,
  oob_score=True,
  bootstrap=True,
  max_depth=20
)

# We used oob_score to track generalization performance. If the OOB score does not improve with additional trees, we can interpret this as a saturation point and stop increasing n_estimators to avoid unnecessary model complexity.

In [25]:
from sklearn.preprocessing import OneHotEncoder

one_hot = OneHotEncoder(sparse_output=False)

In [26]:
categoric_data = X.select_dtypes(include=['category','object']).columns

/var/folders/3s/w63y6jxn56g83g0w4fgb4nh00000gn/T/ipykernel_15945/2892475132.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categoric_data = X.select_dtypes(include=['category','object']).columns

In [27]:
X_train_one_hot = one_hot.fit_transform(X_train[categoric_data])
X_test_one_hot = one_hot.transform(X_test[categoric_data])

In [28]:
encoded_features = one_hot.get_feature_names_out()

In [29]:
X_train_one_hot = pd.DataFrame(X_train_one_hot,columns=encoded_features,index=X_train.index)
X_test_one_hot = pd.DataFrame(X_test_one_hot,columns=encoded_features,index=X_test.index)

In [30]:
X_train = X_train.drop(columns=categoric_data).join(X_train_one_hot)
X_test = X_test.drop(columns=categoric_data).join(X_test_one_hot)

In [31]:
model = randomforest_reg.fit(
  X_train,
  y_train
)

In [36]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
import numpy as np

y_preds = model.predict(X_test)

random_r2 = r2_score(y_test,y_preds)
random_mae = mean_absolute_error(y_test,y_preds)
random_mse = mean_squared_error(y_test,y_preds)
random_rmse = np.sqrt(mean_squared_error(y_test,y_preds))
print(random_r2,random_mae,random_mse,random_rmse)

0.9648043957123332 5557.355171788266 48917090.47084787 6994.075383554846

In [34]:
y.info()

<class 'pandas.Series'>
RangeIndex: 250000 entries, 0 to 249999
Series name: salary
Non-Null Count   Dtype
--------------   -----
250000 non-null  int64
dtypes: int64(1)
memory usage: 1.9 MB

In [35]:
y.mean()

np.float64(145718.080524)